---
title: "Candidate Gene Analysis - Regression method (with controls)"
author: "Amanda Dolinski & Jared J. Homola"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

\pagenumbering{gobble}
   
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("G:/Shared drives/RNA Seq Supershedder Project/BWTE DE manuscript/")
load("candidateGeneAnalysis_regression-Ctl.Rws")
```

```{r message = FALSE, warning = FALSE, echo = FALSE, results = 'hide'}
## Load packages and data
library(tidyverse)
library(kableExtra)
library(edgeR)
library(ggrepel)
```


## Summarize results
```{r, message = FALSE, warning = FALSE, echo = FALSE}
sigResults2 <- sigResults %>% 
  mutate(tmp = paste0(identifier, "-", comparison))

annot2 <- annot.all %>% select(transcript_id, gene_id, sprot_geneName_BlastX) %>%  pivot_longer(cols = transcript_id:gene_id, names_to = "id_type", values_to = "identifier") %>% select(-id_type) %>% distinct(identifier, .keep_all = TRUE)
  
results.table <- allResults %>%
  na.omit() %>% 
  mutate(value = round(value, 4)) %>% 
  mutate(tmp = paste0(identifier, "-", comparison)) %>% 
  pivot_wider(names_from = subset, values_from = value) %>% 
  filter(tmp %in% sigResults2$tmp) %>% 
  select(-tmp) %>% 
  left_join(annot2) %>%
  rename(geneName = sprot_geneName_BlastX) %>% 
  select(identifier, geneName, comparison, Overall, I1, I3, I5, I14)

results.table %>% 
  kbl(booktabs = TRUE, 
      longtable = TRUE,
      caption ="Significant candidate genes when including control samples. In comparison column, BG = Bursa-gene, BT = Bursa-transcript, IG = Ileum-gene, and IT = Ileum-transcript") %>%
  kable_styling(latex_options = c("repeat_header"))

```

```{r, message = FALSE, warning = FALSE, echo = FALSE}
correlationPlot <- function(target, targetTissue, targetLevel, ...) {
  annotation <- annot.all %>%
    filter(transcript_id == target | gene_id == target) %>%
    filter(sprot_geneName_BlastX != ".") %>%
    select(sprot_geneName_BlastX) %>%
    slice(1)
  
  legendData <- allResults %>% 
    filter(identifier == target) %>% 
    mutate(tissue = if_else(comparison == "BG" | comparison == "BT", "Bursa", "Ileum")) %>% 
    mutate(level = if_else(comparison == "BG" | comparison == "IG", "gene", "transcript")) %>% 
    filter(tissue == targetTissue, level == targetLevel)
  
  targetInfo1 <- sigResults %>% 
    filter(identifier == target)
  
  plot <- lcpm.all %>%
    filter(levelGT == targetLevel,
           tissue == targetTissue) %>% 
    filter(identifier == target) %>% 
    ggplot(aes(x = log.virus.sac, y = lcpm)) +
    geom_point(aes(shape = group, color = group), size = 5) +
    geom_smooth(method = "lm", color = "black") +
    ylab("Log2(Counts per million)") +
    xlab("Log10(Sacrifice day viral titer + 1)") +
    scale_shape_manual(values=c(13, 
                                15:18),
                       name = "Group", 
                       labels = c("Ctl",
                                  paste0("I1: ","P-value = ", round(filter(legendData, subset == "I1")$value, 3)), 
                                  paste0("I3: ","P-value = ", round(filter(legendData, subset == "I3")$value, 3)), 
                                  paste0("I5: ","P-value = ", round(filter(legendData, subset == "I5")$value, 3)),
                                  paste0("I14: ","P-value = ", round(filter(legendData, subset == "I14")$value, 3)))) +
    scale_color_manual(values = c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442"),
                       name = "Group", 
                       labels = c("Ctl",
                                  paste0("I1: ","P-value = ", round(filter(legendData, subset == "I1")$value, 3)), 
                                  paste0("I3: ","P-value = ", round(filter(legendData, subset == "I3")$value, 3)), 
                                  paste0("I5: ","P-value = ", round(filter(legendData, subset == "I5")$value, 3)),
                                  paste0("I14: ","P-value = ", round(filter(legendData, subset == "I14")$value, 3)))) +
    guides(shape = guide_legend(override.aes = list(size = 5))) +
    theme_classic() +
    labs(title=paste0(annotation[1], " - ", target),
         subtitle=paste0(targetTissue, " - ", targetLevel,
                         "; Adj. p = ", round(targetInfo1$adj.p.value, 5)))
  print(plot)
}

```

## Plotting significant results
```{r, message = FALSE, warning = FALSE, echo = FALSE, fig.height = 4.5, fig.width= 7.5}
for(z in (1:nrow(results.table))) {
  targetInfo <- results.table %>% 
    slice(z) %>% 
    mutate(tissue = if_else(comparison == "BG" | comparison == "BT", "Bursa", "Ileum")) %>% 
    mutate(level = if_else(comparison == "BG" | comparison == "IG", "gene", "transcript"))

  correlationPlot(targetInfo$identifier, targetInfo$tissue, targetInfo$level)
}
```
